BOC/Areas/CR/Controllers/ControlReportMobileController.cs
using Microsoft.AspNetCore.Mvc;
using BOC.Models;
using BOC.Areas.ControlReport.Models;
using System;
using System.Net.Http;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Nancy.Json;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.FileProviders;
using System.IO;
using System.Threading.Tasks;
using Renci.SshNet;

namespace BOC.Areas.ControlReport.Controllers
{
    [Area("CR")]
    public class ControlReportMobileController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IConfiguration configuration;
        private readonly IFileProvider fileProvider;
        public ControlReportMobileController(IWebHostEnvironment webHostEnvironment, IConfiguration configuration, IFileProvider fileProvider)
        {
            _webHostEnvironment = webHostEnvironment;
            this.fileProvider = fileProvider;
            this.configuration = configuration;


        }
        public IActionResult Index()
        {
            return View();
        }
        public List<RT> GetReportType()
        {

            var token = HttpContext.Session.GetString("Token");
            string Content = API.FO_ReportType_Get(token);
            var oData = JObject.Parse(Content);
            //Bind Json To List 
            JavaScriptSerializer ser = new JavaScriptSerializer();
            List<RT> lst = ser.Deserialize<List<RT>>(oData["Data"].ToString());//str is JSON string.
            return lst;
        }
        public List<FS> GetFlightStage()
        {

            var token = HttpContext.Session.GetString("Token");
            string Content = API.FO_FlightStage_Get(token);
            var oData = JObject.Parse(Content);
            //Bind Json To List 
            JavaScriptSerializer ser = new JavaScriptSerializer();
            List<FS> lst = ser.Deserialize<List<FS>>(oData["Data"].ToString());//str is JSON string.
            return lst;
        }

        public List<DV> GetDivision()
        {
            var token = HttpContext.Session.GetString("Token");
            string Content = API.FO_Division_Get(token);
            var oData = JObject.Parse(Content);
            //Bind Json To List 
            JavaScriptSerializer ser = new JavaScriptSerializer();
            List<DV> lst = ser.Deserialize<List<DV>>(oData["Data"].ToString());//str is JSON string.
            return lst;
        }
        public IActionResult CreateReport(string t_obj)
        {
            string[] obj = t_obj.Split(',');
            
            ViewBag.FlightDate = obj[0];
            ViewBag.FlightNo = obj[1];
            ViewBag.Route = obj[2];
            ViewBag.FlightID = obj[3];
            //Save Session FlightID
            HttpContext.Session.SetString("FlightID", obj[3]);
            ViewBag.Reg = obj[4];
            ViewBag.Aircraft = obj[5];
            ViewBag.ReportType = GetReportType();
            ViewBag.FlightStage = GetFlightStage();
            ViewBag.Division = GetDivision();
            return View();
        }
        [HttpPost]
        public IActionResult CreateReport(FOReport model)
        {
            string strMess = string.Empty;
            var eventdate = DateTime.ParseExact(model.Event_Date, "dd/MM/yyyy", System.Globalization.CultureInfo.InvariantCulture).ToString("yyyy-MM-dd");
            string report_type = model.lst_ReportType_ID;
            string[] typereport = report_type.Split(',');
            // Create list
            var myList = new List<string>();
            foreach (string type in typereport)
            {


                string rp = "{" + '"' + "ReportType_ID" + '"' + ":" + type + "}";
                // Add items to the list
                myList.Add(rp);
            }
            //Tạo chuỗi json Report Type
            var arr = myList.ToArray();
            var json_report_type = JsonConvert.SerializeObject(arr);
            json_report_type = json_report_type.Replace(@"\", "").Replace(@"""{", "{").Replace(@"}""", "}");
            string division = model.lst_RpDivID;
            string[] dv = division.Split(',');
            // Create list
            var lstdiv = new List<string>();
            foreach (string d in dv)
            {
                string div = "{" + '"' + "RpDivID" + '"' + ":" + d + "}";
                // Add items to the list
                lstdiv.Add(div);
            }
            //Tạo chuỗi json Division
            var dvs = lstdiv.ToArray();
            var json_division = JsonConvert.SerializeObject(dvs);
            json_division = json_division.Replace(@"\", "").Replace(@"""{", "{").Replace(@"}""", "}");


            string flightphase = model.lst_FlightStage_ID;
            string[] fp = flightphase.Split(',');
            // Create list
            var lstfp = new List<string>();
            foreach (string f in fp)
            {
                string fs = "{" + '"' + "FlightStage_ID" + '"' + ":" + f + "}";
                // Add items to the list
                lstfp.Add(fs);
            }
            //Tạo chuỗi json Flight Phase
            var fps = lstfp.ToArray();
            var json_flightphase = JsonConvert.SerializeObject(fps);
            json_flightphase = json_flightphase.Replace(@"\", "").Replace(@"""{", "{").Replace(@"}""", "}");

            //Get Session Token
            var token = HttpContext.Session.GetString("Token");
            //Get Session FlightID
            model.FlightID = Int32.Parse(HttpContext.Session.GetString("FlightID"));
            //Get Session Object Attach File
            var _attachfileList = SessionHelper.GetObjectFromJson<List<FileAttach>>(HttpContext.Session, "FileAttach");
            // Create list
            var lstfa = new List<string>();
            foreach (var _attachfile in _attachfileList)
            {
                if (_attachfile.Status == "OK")
                {
                    string fileattached = "{" + '"' + "FileLoc_ID" + '"' + ":" + _attachfile.FileLoc_ID + "}";
                    // Add items to the list
                    lstfa.Add(fileattached);
                }
            }
            //Tạo chuỗi json Attached File Upload
            var fas = lstfa.ToArray();
            var json_fa = JsonConvert.SerializeObject(fas);
            json_fa = json_fa.Replace(@"\", "").Replace(@"""{", "{").Replace(@"}""", "}");

            //Call api to update Report
            string Content = API.FO_Report_Update(model.FlightID, 1, model.ReportDate.ToString("yyyy-MM-dd"), model.Event_Location, model.Event_Time,
                eventdate, model.Description, model.Content, model.Reccomendation, "OK", json_report_type, json_division, json_flightphase, json_fa, 0, token);
            var oData = JObject.Parse(Content);
            if (oData["ResultCode"].ToString() == "0")
            {
                return Json(new { mess = "OK" });

            }
            else
            {
                strMess = oData["Message"].ToString();
            }
            return Json(new { mess = strMess });
        }

        [HttpPost]
        public async Task<IActionResult> UploadFileAttach(FOReport model)
        {
            var host = configuration["SFTP:Host"];
            var port = configuration["SFTP:Port"];
            var username = configuration["SFTP:Username"];
            var password = configuration["SFTP:Password"];
            string strMess = string.Empty;
            var token = HttpContext.Session.GetString("Token");


            model.FileAttached = new List<FileAttach>();
            foreach (var file in model.Files)
            {
                //Call api to get BagHS_Found
                string Content = API.FO_sFTP_FileName_Get(file.FileName.ToString(), token);
                var oData = JObject.Parse(Content);
                var FileLoc_ID = oData["Data"]["ID"].ToString();
                model.pathSFTP = oData["Data"]["Folder"].ToString();
                model.FileName = oData["Data"]["FileName"].ToString();
                model.lst_Attached_Files += FileLoc_ID + ",";
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/data/ControlReport/", model.FileName);
                //Upload file len web server
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    try
                    {
                        await file.CopyToAsync(stream);
                    }
                    catch (Exception ex)
                    {
                        strMess = ex.Message;
                        return Json(new { mess = strMess });
                    }
                }
                //Upload File To SFTP
                using (var client = new SftpClient(host, Int16.Parse(port), username, password))
                {
                    client.Connect();
                    if (client.IsConnected)
                    {
                        try
                        {
                            //Call Api Upload SFTP File
                            API.UploadSFTPFile(host, username, password, path, model.pathSFTP, Int32.Parse(port));

                        }
                        catch (Exception ex)
                        {
                            strMess = ex.Message;
                            return Json(new { mess = strMess });
                        }



                    }
                }

                FileAttach fd = new FileAttach();
                fd.ReportID = 0;
                fd.FileLoc_ID = Int32.Parse(FileLoc_ID.ToString());
                fd.FileName = file.FileName.ToString();
                fd.sysFileName = model.FileName;
                fd.Status = "OK";
                model.FileAttached.Add(fd);


            }
            //SAVE Session object AttachedFile

BOC/Areas/CR/Views/ControlReportMobile/CreateReport.cshtml
@{
    ViewData["Title"] = "CreateReport";
    Layout = "~/Views/Shared/_Mobile.cshtml";
}
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
@{

    var email = @HttpContextAccessor.HttpContext.Session.GetString("Email");
    var date = System.DateTime.Today.ToString("yyyy-MM-dd");

}




 <style>
   .glyphicon-calendar {
    font-size: 15pt;
}

.input-group {
    width: 180px;
    margin-top: 30px;
}

</style>




   @* <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css' media="screen" />*@

     <link rel="stylesheet" href='~/css/controlreport/bootstrap.min.css' media="screen" />
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css">
    <!-- Bootstrap DatePicker -->
 @*   <link rel="stylesheet" href="~/css/controlreport/bootstrap-datepicker.css" type="text/css" />*@
    <link rel="stylesheet" href="~/css/controlreport/CreateReport.css" type="text/css" />

<h1 id="title">Tạo Báo Cáo/CreateReport</h1>
<p id="note">
    Note: <b>Thời gian sử dụng theo mốc GMT+7</b> /<br /> Usage time according to GMT+7
</p>
<div class="box">
    <p id="note">
        <b>Bạn đang tạo báo cáo cho chuyến bay<br />@ViewBag.FlightDate.ToString()/@ViewBag.FlightNo.ToString()/@ViewBag.Route.ToString(). Số đăng ký máy bay @ViewBag.Reg.ToString(). Số tàu bay @ViewBag.Aircraft.ToString().</b>
    </p>
    <p style="text-align:center;">------------------</p>
    <p id="note">
        You are creating a report for flight<br />@ViewBag.FlightDate.ToString()/@ViewBag.FlightNo.ToString()/@ViewBag.Route.ToString(). The aircraft registration number is @ViewBag.Reg.ToString(). The aircraft number is @ViewBag.Aircraft.ToString().
    </p>
    <div class="row" style="margin-left:10px;"><p id="required"><b>Người báo cáo</b>/ Reporter</p></div>
    <div class="row" style="margin-left:10px;">
        @* @Html.TextBoxFor(model => model.Reporter, new {  id = "reporter", @class = "form-control" })*@
        <input type="text" id="email" style="width:260px;" value="@email"/>
    </div>
    <div class="row" style="margin-left:10px;margin-top:10px;"><p id="required"><b>Ngày báo cáo</b>/ Report date</p></div>
    <div class="row" style="margin-left:10px;">
        @* @Html.TextBoxFor(model => model.ReportDate, new {  id = "reporter", @class = "form-control" })*@
         <input type="date" id="reportdate" style="width:260px;" value="@date"/>
    </div>
    <div class="row" style="margin-left:10px;margin-top:10px;"><p id="required"><b>LOẠI BÁO CÁO</b>/ REPORT TYPE</p></div>
    <div class="row" style="margin-left:87px;">
         <select id="reporttype"  name="reporttype" multiple>
             @foreach (var item in ViewBag.ReportType)
             {

                    <option value="@item.ReportType_ID">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@item.Description.ToString()</option>

               }
         </select>
    </div>
    <div class="row" style="margin-left:10px;margin-top:10px;"><p id="required"><b>Mã sự cố </b>/ Incident code</p></div>
    <div class="row" style="margin-left:10px;margin-top:10px;">
        @* @Html.TextBoxFor(model => model.IncidentCode, new {  id = "reporter", @class = "form-control" })*@
         <input type="text" id="incidentcode" style="width:260px;"/>
    </div>
    <div class="row" style="margin-left:10px;margin-top:10px;"><p id="required"><b>Mô tả sự cố</b>/ Description of the incident</p></div>
    <br />
    <div class="row" style="margin-left:10px;">
        <textarea class="form-control" id="description" rows="4" placeholder="Mô tả sự cố / Description of the incident" maxlength="1000" style="margin-top:-20px;width:260px;"></textarea>
    </div>
    <div class="row" style="margin-left:10px;margin-top:10px;">
         <p style="width:280px;"><b>CHI TIẾT VỀ SỰ VỤ / UY HIẾP AN TOÀN / THƯƠNG TẬT</b>/ INCIDENT/ HAZARD/ INJURY DETAIL</p>
    </div>
    <br />
     <div class="row" style="margin-left:10px;margin-top:10px;margin-top:10px;"><p id="required"><b>Ngày xảy ra sự cố</b>/ Date of incident</p></div>
     <div class="row" style="margin-left:10px;">
           <div class="input-group datepicker">
                                <input id="txtDate" type="text" class="form-control date-input" readonly="readonly" style="margin-top:-60px;width:210px;"/>
                                <label class="input-group-btn" for="txtDate">
                                    <span class="btn btn-default" style="margin-top:-60px;">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </label>
            </div>
     </div>
     <div class="row" style="margin-left:10px;margin-top:10px;"><p id="required"><b>Nơi xảy ra sự cố</b>/ Location of incident</p></div>
     <div class="row" style="margin-left:10px;margin-top:10px;">
         <input type="text" id="txtlocation"  style="width:260px;"/>
     </div>
     <div class="row" style="margin-left:10px;margin-top:10px;width:280px;"><p id="required"><b>Thời gian xảy ra sự cố</b>/ Local Time of incident</p></div>
     <div class="row" style="margin-left:10px;">
         <input type="text" id="txtlocaltime" style="width:260px;"/>
     </div>
     <div class="row" style="margin-left:10px;margin-top:10px;width:280px;"><p id="required"><b>Bộ phận có liên quan đến sự cố</b>/ Division related to incident</p></div>
     <div class="row" style="margin-left:87px;">
          <select id="divisionrelated"  name="divisionrelated" multiple>
              @foreach (var item in ViewBag.Division)
              {

                    <option value="@item.RpDivID">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@item.DivisionName.ToString()</option>

               }

         </select>
     </div>
     <div class="row" style="margin-left:10px;margin-top:10px;"><p id="required"><b>Giai đoạn bay</b> / Flight phase</p></div>
     <div class="row" style="margin-left:87px;">
          <select id="flightphase"  name="flightphase" multiple>
              @foreach (var item in ViewBag.FlightStage)
              {

                    <option value="@item.FlightStage_ID.ToString()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@item.Description.ToString()</option>

               }

         </select>
     </div>
      <div class="row" style="margin-left:10px;margin-top:10px;"><p id="required"><b>NỘI DUNG BÁO CÁO</b>/ REPORT CONTENT</p></div>
     <div class="row" style="margin-left:10px;">
         <div class="box2">
             <b>Mô tả sự cố (Vui lòng mô tả rõ ràng và ngắn gọn về sự cố). – LOẠI SỰ CỐ / VỊ TRÍ / CÁ NHÂN , ĐƠN VỊ LIÊN QUAN / THỜI GIAN / LÝ DO /
CÁCH THỨC – có thể bổ sung thêm trang khác khi cần thiết.</b>/
Description (Please give a clear and concise description of events). - WHAT / WHERE / WHO / WHEN / WHY / HOW - Additional pages can be added as necessary.
            <br />
            <textarea class="form-control" id="reportcontent" rows="4" placeholder="Mô tả sự cố" maxlength="1000" style="margin-top:4px;margin-left:10px;margin-bottom:10px;width:235px;"></textarea>
         </div>
         <div class="row" style="margin-left:10px;margin-top:10px;"><p><b>KIẾN NGHỊ</b>/ RECOMMENDATION</p></div>
          <div class="row" style="margin-left:10px;">
                <textarea class="form-control" id="description" rows="4" placeholder="Nhập kiến nghị những biện pháp nhằm đảm bảo An toàn/RECOMMENDATION (if any)" maxlength="1000" style="margin-top:4px;margin-left:10px;width:235px;"></textarea>
          </div>
          <div class="row" style="margin-left:10px;margin-top:10px;"><p id="required"><b>ĐÍNH KÈM</b>/ ATTACHMENTS</p></div>
          <br />
           <div class="row" style="margin-left:20px;" id="files">

                                    <div class="row" style="margin-left: 20px;">
                                        <label for="file-upload" class="custom-file-upload">
                                            <img src="/images/attach.png" width="20" height="20" />&nbsp;&nbsp;Attach File
                                        </label>
                                        <input type="file" id="fileToUpload" multiple />
                                    </div>

                                    <div class="row" style="width:300px;">
                                        <ul class="fileList" id="list">
                                        </ul>
                                    </div>
            </div>
             <div class="row" style="margin-left:10px;margin-top:10px;width: 280px;"><p><b>NỘI DUNG PHẢN HỒI</b>/ RESPONSE CONTENT</p></div>
              <div class="row" style="margin-left:10px;">
                    <textarea class="form-control" id="reportcontent" rows="4" placeholder="Admin gửi ý kiến phản hồi tại đây" maxlength="1000" style="margin-top:4px;margin-left:10px;width:235px;"></textarea>
              </div>
               <div class="row" style="margin-left:10px;margin-top:10px;">
                  <button type="button" id="savedraft" class="btn btn-primary" style="width:200px;">Lưu Nháp/ Save Draft</button>
                  <button type="button" id="sendreport" class="btn btn-success" style="width:200px;margin-top:5px;">Gửi Báo Cáo/ Send Report</button>
              </div>

               <br />
               <br />
     </div>
</div>
 <div id="loading-div-background" style="visibility:hidden;">
                <div id="loading-div" class="ui-corner-all">
                    <img style="height:80px;margin:30px;" src="/images/loading.gif" alt="Loading.." />
                    <h2 style="color:gray;font-weight:normal;">Please wait....</h2>
                </div>
  </div>
<script src="~/js/controlreport/Mcreatereport.js"></script>
@* <script type="text/javascript">
       $(document).ready(function() {
           document.getElementById("incidentcode").disabled = true;
            $('#reporttype').multiSelect();
            $('#divisionrelated').multiSelect();
            $('#flightphase').multiSelect();
           
             $('.datepicker').click(
                    function () {
                             $('#txtDate').datepicker({
                                format: "dd/mm/yyyy",
                                orientation: 'bottom',
                                autoclose:true
                            });
                    }
                );
         
              //Dùng để open fileUpload
                $('.custom-file-upload').bind('touchstart click', function () {
                    $('#fileToUpload').click();
                });
         
        });
    </script>
*@

BOC/Areas/CR/Views/ControlReportMobile/FlightGet.cshtml
@{
    ViewData["Title"] = "FlightGet";
    Layout = "~/Views/Shared/_Mobile.cshtml";
}

@using DevExtreme.AspNet.Mvc
@using BOC.Areas.ControlReport.Models;
@model ControlReportModel;
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
@{
    var sessionName = new Byte[20];
    bool nameOK = Context.Session.TryGetValue("Username", out sessionName);
    var sessionToken = @HttpContextAccessor.HttpContext.Session.GetString("Token");

}


 <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css' media="screen" />

@*    <link rel="stylesheet" href='~/css/controlreport/bootstrap.min.css' media="screen" />*@
    <!-- Bootstrap DatePicker -->
    <link rel="stylesheet" href="~/css/controlreport/bootstrap-datepicker.css" type="text/css" />

<h4 style="text-align:center;margin-top:100px;">Hi @HttpContextAccessor.HttpContext.Session.GetString("Username"), please choose your flight date:</h4>


  
       <div class="row" style="text-align:center;margin-top:60px;">
            
                <div class="form-group col-xs-4" style="margin-left: 80px;">
                                <div class="input-group">
                                    @Html.TextBoxFor(m => m.FromDate, new { @class="form-control date-input",id="txtfromDate",@readonly="readonly", @style="margin-top:-60px;width:210px;" })
                                    <label class="input-group-btn" for="txtfromDate">
                                        <span class="btn btn-default" style="margin-top:-60px;">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                          
                                        </span>
                                    </label>
                                </div>
                     
                </div>
                 @Html.HiddenFor(model => model.FromDate)
                <p style="margin-left:-22px;">------</p>

                 <div class="form-group col-xs-4" style="margin-left:80px;margin-top:50px;">
                                <div class="input-group">
                                     @Html.TextBoxFor(m => m.ToDate, new { @class="form-control date-input",id="txttoDate",@readonly="readonly", @style="margin-top: -110px;width:210px" })
                                    <label class="input-group-btn" for="txttoDate">
                                        <span class="btn btn-default" style="margin-top:-110px;">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                           
                                        </span>
                                    </label>
                                </div>
                            
                </div>
                @Html.HiddenFor(model => model.ToDate)
       </div>

       <button class="btn btn-primary" ontouchstart="clickSearch()" style="margin-left: 170px;margin-top:-42px;"  id="search">Search</button>
    
   <br />
@if (Model != null)
{
    <input type="hidden" id="error" value="@Model.ErrorMessage" />
}
   
  
    <script type="text/javascript">
       $(document).ready(function() {
            var firstDay = (new Date().getMonth() + 1) + "/01/" + new Date().getFullYear();


            var today = new Date();
            var dd = String(today.getDate()).padStart(2, '0');
            var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
            var yyyy = today.getFullYear();
            today = mm + '/' + dd + '/' + yyyy;
            var now = new Date();
            var datepick = new Date(now);
            /*Thiết lập ngày mặc định cho datepicker*/


            $('#txtfromDate').datepicker({
                weekStart: 1,
                daysOfWeekHighlighted: "6,0",
                autoclose: true,
                todayHighlight: true,
                format: 'dd/mm/yyyy',
                zIndexOffset: '1001'
               

            });
            
            if (datepick != null) {
                $("#txtfromDate").datepicker("setDate", datepick);
            }
        
             $('#txttoDate').datepicker({
                weekStart: 1,
                daysOfWeekHighlighted: "6,0",
                autoclose: true,
                todayHighlight: true,
                format: 'dd/mm/yyyy',
                zIndexOffset: '1001'
            });
             if (datepick != null) {
                $("#txttoDate").datepicker("setDate", datepick);
            }

            if ($("#error").val() != null && $("#error").val() != "") {
                alertify.alert($("#error").val());
                return false;

            }

            
           
 
    });
         
       
    </script>
    <script>
      
    
        function clickSearch() {

                var formData = new FormData();
                var t_fromDate = $("#txtfromDate").val();
                console.log(t_fromDate);
                if (t_fromDate === "") {
                    alertify.alert('FromDate not be blank!');
                    return false;
                }
                else {
                    formData.append("FromDate", t_fromDate);
                }

                var t_toDate = $("#txttoDate").val();
                console.log(t_toDate);
                if (t_toDate === "") {
                    alertify.alert('ToDate not be blank!');
                    return false;
                }
                else {
                    formData.append("ToDate", t_toDate);
                }

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("FlightGet", "ControlReportMobile")',
                    data: formData,
                    processData: false,
                    contentType: false,
                    cache: false,
                    success: function (data) {
                          if (data.mess == "OK") {
                           return window.location.href="/CR/ControlReportMobile/FlightList";
                        }
                        //else{
                        //      alertify.alert(data.mess);
                        //     return false;
                        //}

                    },
                    error: function (data) {
                        alertify.alert(data.mess);
                        return false;
                    }

                });
        }
    </script>
  

BOC/Areas/CR/Views/ControlReportMobile/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Mobile.cshtml";
}

<style>
   .glyphicon-calendar {
    font-size: 15pt;
}

.input-group {
    width: 180px;
    margin-top: 30px;
}

</style>




    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css' media="screen" />

    @*<link rel="stylesheet" href='~/css/controlreport/bootstrap.min.css' media="screen" />*@
    <!-- Bootstrap DatePicker -->
    <link rel="stylesheet" href="~/css/controlreport/bootstrap-datepicker.css" type="text/css" />

   

 
    <h1 style="color:red;text-align:center;margin-top:100px;"><b>Tìm kiếm báo cáo</b>/ Report search area</h1>
    <br />
    <div class='container' style="margin-top:120px;">
        <div class="row" style="margin-left:50px!important;"> 
            <div style="margin-left:16px;"><b>Ngày báo cáo</b>/ Report date:</div>
        </div>
        <br />
        <div class="row" style="margin-left:50px!important;">
             <div class="form-group col-xs-4" >
                            <div class="input-group">
                                <input id="txtfromDate" type="text" class="form-control date-input" readonly="readonly" style="margin-top:-60px;width:210px;"/>
                                <label class="input-group-btn" for="txtfromDate">
                                    <span class="btn btn-default" style="margin-top:-60px;">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </label>
                            </div>
            </div>
       </div>
       <div class="row" style="margin-left:50px!important;">
             <div class="form-group col-xs-4">
                            <div class="input-group">
                                <input id="txttoDate" type="text" class="form-control date-input" readonly="readonly" style="margin-top:-60px;width:210px;"/>
                                <label class="input-group-btn" for="txttoDate">
                                    <span class="btn btn-default" style="margin-top:-60px;">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </label>
                            </div>
            </div>
        </div>
       <div class="row" style="margin-left:50px!important;"> 
            <div style="margin-left:16px;"><b>Từ khóa</b>/ Key search:</div>
         </div>
        <div class="row" style="margin-left:52px!important;">
            <input type="text" id="keysearch" style="width:247px;margin-left:16px;"/>
       </div>
       <br />
        <div class="row" style="margin-left:67px!important;"> 
             <b>Trạng thái báo cáo</b>/ Report status:
        </div>
         <div class="row" style="margin-left: 176px!important;"> 
            
                <select id="reportstatus"  name="reportstatus" multiple>
                    <option value="Draft">&nbsp;&nbsp;&nbsp;&nbsp;Draft</option>
                    <option value="Deleted">&nbsp;&nbsp;&nbsp;&nbsp;Deleted</option>
                    <option value="Waiting accept">&nbsp;&nbsp;&nbsp;&nbsp;Waiting accept</option>
                    <option value="Accepted">&nbsp;&nbsp;&nbsp;&nbsp;Accepted</option>
                    <option value="Risk assessment">&nbsp;&nbsp;&nbsp;&nbsp;Risk assessment</option>
                </select>
       </div>
       <br />
       <div style="margin-left:64px;">
           <input type="button" value="Tìm kiếm/ Search" class="btn btn-primary" />
       </div>
    </div>


    <script type="text/javascript">
       $(document).ready(function() {
            $('#reportstatus').multiSelect();

            $('#txtfromDate').datepicker({
                format: "dd/mm/yyyy"
            });
             $('#txttoDate').datepicker({
                format: "dd/mm/yyyy"
            });
         
        });
    </script>

BOC/Areas/CR/Views/ControlReportMobile/ReportList.cshtml
@{
    ViewData["Title"] = "ReportList";
    Layout = "~/Views/Shared/_Mobile.cshtml";
}

<h1 style="margin-top:100px;">ReportList</h1>